### ISSUE TITLE
Begin & Complete callbacks firing for both enter and leave.

### ISSUE THREAD

**Issue by SethTompkins** [twitter-fabric/velocity-react#80] opened 2016-03-07 18:52 UTC
Example: 

```javascript
<VelocityTransitionGroup
 enter={{animation: "slideDown", duration: 250}}
 leave={{
   animation: "slideUp",
   begin: (element) => {
     console.log(element);
   },
   duration: 250
 }}
>
```

The `begin` callback on the leave animation will fire when the enter animation triggers as well, not just when the leave animation is triggered.

**Comment by phopkins** [comment] 2016-03-07 19:50
This is currently by design because the leave animation is run to completion before an element is added, so that elements can base their enter animations off of a consistent “left” state.

I think I’d be open to a patch that would not run either of the “leave” callbacks in this case, however.

**Comment by SethTompkins** [comment] 2016-03-07 21:17
Hrmm, this is the line right here correct?

https://github.com/twitter-fabric/velocity-react/blob/eed8a4077e5589bc38e5d42eaffc2457449b2cdd/velocity-transition-group.js#L181

Would it make sense to simply exclude the `begin` opt there just as the `complete` opt is excluded?

**Comment by phopkins** [comment] 2016-03-07 21:20
Yeah, that works for me.

**Comment by phopkins** [comment] 2016-03-09 21:28
Will be fixed in 1.1.4

**Comment by Kerumen** [comment] 2016-03-16 10:37
> This is currently by design because the leave animation is run to completion before an element is added, so that elements can base their enter animations off of a consistent “left” state.

Please specify this somewhere in the doc. I just lost merely 2 hours wondering why my elements started with the props of the leave animation..

**Comment by finneganh** [comment] 2016-03-17 14:29
Yeah, good point. Looks like that's not documented outside of the `VelocityTransitionGroup` source code.

**Comment by finneganh** [comment] 2016-04-12 02:00
Adding this for the next rev of the README.

**Closed by finneganh** 2016-04-12 02:00 UTC
