### ISSUE TITLE
using jsdom to test ReactComponent with velocity-react will throw error

### ISSUE THREAD

**Issue by Tomyail** [twitter-fabric/velocity-react#119] opened 2016-08-25 12:45 UTC
For some reason, I need a fake window for node test environment. So I use [jsdom](https://github.com/tmpvar/jsdom).But this will cause a problem that `velocity-animate-shim.js` export an truly Velocity for me. And the detail error stack is as follow:
```
Velocity UI Pack: Velocity must be loaded first. Aborting.

/Users/user/mywork/node_modules/velocity-react/velocity-helpers.js:71
    throw "Velocity.RegisterEffect not found. You need to require('velocity-animate/velocity.ui') at a top level for UI Pack.";
    ^
Velocity.RegisterEffect not found. You need to require('velocity-animate/velocity.ui') at a top level for UI Pack.
```

**Comment by finneganh** [comment] 2016-09-19 19:51
Added a review to that PR. I know it's been a little while. LMK if you want to update the PR or I can take over the fix.

**Comment by finneganh** [comment] 2016-09-28 18:15
Just merged. Will be in the next release.

**Closed by finneganh** 2016-09-28 18:15 UTC

**Comment by finneganh** [comment] 2016-10-03 14:01
I've been looking into this a little more. In my tests, loading the demo with jsdom worked. I couldn't reproduce the require error.

I'm not sure there's a particular reason why velocity-react shouldn't work with jsdom around, and I wonder if the require error you have is from something else. Leaving the jsdom exclusion in for now, but that might get revisited if it comes up as a feature request from someone else.

**Comment by Tomyail** [comment] 2016-10-04 13:40
I use ava and enzyme to test my component. And I reproduce this error on my [branch]( https://github.com/Tomyail/velocity-react/tree/jsdom).when run `npm run test`,the error occur. And `npm run test-shim` is my solution.
